POST http://localhost:8080/admin/signup
Content-Type: application/json

{
    "name":"madhavi",
    "company":"u3tech",
    "email":"madhavimandraju@gmail.com",
    "password":"6303738847",
    "contact":"630s37238847",
    "User_type":"ADMIN"
}

###
POST http://localhost:8080/admin/login
Content-Type: application/json

 {
    "Email":"sribabum2andraju@gmail.com",
    "Password":"63037s22ribabu"
 }

 # Headers
Authorization: HELLO_WORLD

###
POST http://localhost:8080/client/signup
Content-Type: application/json

{
    "Email": "user12@example.com",
    "Name": "Johnfde Doe",
    "Company": "ABCDESF Corp",
    "Password": "secresstpassword2",
    "Contact": "12345s678902"
}


###

POST http://localhost:8080/client/login
Content-Type: application/json
Authorization: HELLO_WORLD

 {
    "Email":"user1@example.com",
    "Password":"secretpassword2"
 }

 # Headers
Authorization: HELLO_WORLD


###
GET http://localhost:8080/admin/allAdmins
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNyaWJhYnVtMmFuZHJhanVAZ21haWwuY29tIiwiTmFtZSI6InNyaWJhYjJ1IiwiQ29udGFjdCI6IjYzMHMzNzIzODg0NyIsIlBhc3N3b3JkIjoiIiwiQ29tcGFueSI6ImFtYXMyem9uIiwiVXNlcl9pZCI6IjY1YzBjNTQ0ZWYzYTFiNDAxMmM1Zjg4OSIsImV4cCI6MTcwNzMwOTY2NH0.Ut7s2Xu_GfmncJfJQagnJcJYmu3-RcKpmlmIrpNnuPE


###
POST http://localhost:8080/admin/sendRequest
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNyaWJhYnVtMmFuZHJhanVAZ21haWwuY29tIiwiTmFtZSI6InNyaWJhYjJ1IiwiQ29udGFjdCI6IjYzMHMzNzIzODg0NyIsIlBhc3N3b3JkIjoiIiwiQ29tcGFueSI6ImFtYXMyem9uIiwiVXNlcl9pZCI6IjY1YzBjNTQ0ZWYzYTFiNDAxMmM1Zjg4OSIsImV4cCI6MTcwNzMwOTY2NH0.Ut7s2Xu_GfmncJfJQagnJcJYmu3-RcKpmlmIrpNnuPE

{
  "name": "sribabu1",
  "send_by": "the processdd",
  "discription": "mdddde",
  "short_discription": "i am grddeat"
}

###
GET  http://localhost:8080/admin/all-requests
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNyaWJhYnVtMmFuZHJhanVAZ21haWwuY29tIiwiTmFtZSI6InNyaWJhYjJ1IiwiQ29udGFjdCI6IjYzMHMzNzIzODg0NyIsIlBhc3N3b3JkIjoiIiwiQ29tcGFueSI6ImFtYXMyem9uIiwiVXNlcl9pZCI6IjY1YzBjNTQ0ZWYzYTFiNDAxMmM1Zjg4OSIsImV4cCI6MTcwNzY1MzI2NX0._bDlmihvtiJssfRwVzUb3qRoT9LpVrY4ox_q2qMu2ZA


###

PUT  http://localhost:8080/admin/modify-request/65c25c9f8b0befe3d15a3f54 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNyaWJhYnVtMmFuZHJhanVAZ21haWwuY29tIiwiTmFtZSI6InNyaWJhYjJ1IiwiQ29udGFjdCI6IjYzMHMzNzIzODg0NyIsIlBhc3N3b3JkIjoiIiwiQ29tcGFueSI6ImFtYXMyem9uIiwiVXNlcl9pZCI6IjY1YzBjNTQ0ZWYzYTFiNDAxMmM1Zjg4OSIsImV4cCI6MTcwNzY1MzI2NX0._bDlmihvtiJssfRwVzUb3qRoT9LpVrY4ox_q2qMu2ZA

{
  
  "action": "Rejected"
}
###
GET http://localhost:8080/admin/adminInfo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InNyaWJhYnVtMmFuZHJhanVAZ21haWwuY29tIiwiTmFtZSI6InNyaWJhYjJ1IiwiQ29udGFjdCI6IjYzMHMzNzIzODg0NyIsIlBhc3N3b3JkIjoiIiwiQ29tcGFueSI6ImFtYXMyem9uIiwiVXNlcl9pZCI6IjY1YzBjNTQ0ZWYzYTFiNDAxMmM1Zjg4OSIsImV4cCI6MTcwNzIzODA5OX0.rQs705Ku3EfMDgSsBEUOSik31Odk5FqRY8L7WZgac8A

###
GET  http://localhost:8080/admin/client/all-clients 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im1hZGhhdmltYW5kcmFqdUBnbWFpbC5jb20iLCJOYW1lIjoibWFkaGF2aSIsIkNvbnRhY3QiOiI2MzBzMzcyMzg4NDciLCJQYXNzd29yZCI6IiIsIkNvbXBhbnkiOiJ1M3RlY2giLCJVc2VyX2lkIjoiNjVjNzZiMzI2MjVmMTkyNDRhZDhlOTVjIiwiZXhwIjoxNzA3NjU0MzIyfQ.uNZcjS2a_jKhoaWYvhz_QL6iqy-9S7L4i4ijUgPSdHU


###

GET  http://localhost:8080/admin/client/65b906c56b2a79046a9b5e35
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6Im1hZGhhdmltYW5kcmFqdUBnbWFpbC5jb20iLCJOYW1lIjoibWFkaGF2aSIsIkNvbnRhY3QiOiI2MzBzMzcyMzg4NDciLCJQYXNzd29yZCI6IiIsIkNvbXBhbnkiOiJ1M3RlY2giLCJVc2VyX2lkIjoiNjVjNzZiMzI2MjVmMTkyNDRhZDhlOTVjIiwiZXhwIjoxNzA3NjU0MzIyfQ.uNZcjS2a_jKhoaWYvhz_QL6iqy-9S7L4i4ijUgPSdHU

