POST http://localhost:8080/admin/signup
Content-Type: application/json

{
    "Name":"madhavi",
    "Email":"madhavimandraju@gmail.com",
    "Password":"6303738847"
}

###
POST http://localhost:8080/admin/login
Content-Type: application/json

 {
    "Email":"madhavimandraju@gmail.com",
    "Password":"6303738847"
 }

 ###
 
